---
- name: NMAP hosts and report
  hosts: localhost
  remote_user: vboxuser # ot imeni kogo stuchimsya
  become: true          # povishaem privelegii
  become_method: sudo   # chem previshaem
  gather_facts: no      # sobiraem facti ili net

  tasks:

  - name: Install NMAP
    apt:
        name: nmap
        state: latest
        update_cache: True

  - name: Copy nmap targets list
    copy:
        src: ./targets.txt
        dest: ~/targets.txt
        force: yes
        mode: 0644

  - name: Run nmap
    shell: "nmap -iL ~/targets.txt -p 80 -oG -"
    register: nmap_result

  - name: Nmap output
    debug:
        msg: "{{ nmap_result.stdout_lines }}" # vivodit soobshenie na ekra
